export const PATCHES = {
  electronPatch: {
    name: 'Electron Patches',
    description: 'Required for client functionality. Automatically enabled on desktop client.',
    authors: ['Oldcord Team'],
    mandatory: false,
    configurable: false,
    defaultEnabled: false,
    compatibleBuilds: 'all',
    incompatiblePatches: [],
  },
  userSelect: {
    name: 'User Select',
    description: 'Enables user selection in 2015 clients',
    authors: ['Oldcord Team'],
    mandatory: false,
    configurable: true,
    defaultEnabled: true,
    compatibleBuilds: '2015',
    incompatiblePatches: [],
  },
  emojiAnywhere: {
    name: 'Unrestricted Emojis',
    description: 'Allows using emojis anywhere without restrictions',
    authors: ['Oldcord Team'],
    mandatory: false,
    configurable: true,
    defaultEnabled: true,
    compatibleBuilds: 'all',
    incompatiblePatches: [],
  },
  forceWebRtcP2P: {
    name: 'Force WebRTC P2P',
    description:
      'Forces the client to use webrtc-p2p instead of webrtc, this means, small-scale voice calling without the need for a media server',
    authors: ['Oldcord Team'],
    mandatory: false,
    configurable: true,
    defaultEnabled: false,
    compatibleBuilds: [
      'january_31_2017',
      'march_30_2017',
      'may_3_2017',
      'may_17_2017',
      'july_20_2017',
      'august_17_2017',
      'september_28_2017',
      'october_5_2017',
      'november_16_2017',
      'december_21_2017',
      'january_25_2018',
      'february_25_2018',
      'march_7_2018',
      'april_1_2018',
      'april_23_2018',
      'may_28_2018',
      'june_29_2018',
      'august_28_2018',
      'september_29_2018',
      'november_30_2018',
      'december_31_2018',
    ],
    incompatiblePatches: [],
  },
};
